// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-k7aDHICpe_WkYZJgk8L_iIDpKo_KP8',
    appId: '1:22806321081:web:163673658d47b46ba3c868',
    messagingSenderId: '22806321081',
    projectId: 'crud-yogesh',
    authDomain: 'crud-yogesh.firebaseapp.com',
    databaseURL: 'https://crud-yogesh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-yogesh.appspot.com',
    measurementId: 'G-KH49Q05NBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlsyogoYGb9SN2xDU6VVLIpvml_SQcj2U',
    appId: '1:22806321081:android:183040f027629557a3c868',
    messagingSenderId: '22806321081',
    projectId: 'crud-yogesh',
    databaseURL: 'https://crud-yogesh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-yogesh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZaIyIK3dJuNp2lVkwhTuub-c3M5PGnnk',
    appId: '1:22806321081:ios:c21875fb6baaa469a3c868',
    messagingSenderId: '22806321081',
    projectId: 'crud-yogesh',
    databaseURL: 'https://crud-yogesh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-yogesh.appspot.com',
    iosBundleId: 'com.example.boilerplateNewVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZaIyIK3dJuNp2lVkwhTuub-c3M5PGnnk',
    appId: '1:22806321081:ios:c21875fb6baaa469a3c868',
    messagingSenderId: '22806321081',
    projectId: 'crud-yogesh',
    databaseURL: 'https://crud-yogesh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-yogesh.appspot.com',
    iosBundleId: 'com.example.boilerplateNewVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-k7aDHICpe_WkYZJgk8L_iIDpKo_KP8',
    appId: '1:22806321081:web:c4a822472fcb31c1a3c868',
    messagingSenderId: '22806321081',
    projectId: 'crud-yogesh',
    authDomain: 'crud-yogesh.firebaseapp.com',
    databaseURL: 'https://crud-yogesh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-yogesh.appspot.com',
    measurementId: 'G-3NB9QME5PN',
  );
}
